/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin._authenticated.index'
import { Route as AdminAuthenticatedUsersRouteImport } from './routes/admin._authenticated.users'
import { Route as AdminAuthenticatedToolsRouteImport } from './routes/admin._authenticated.tools'
import { Route as AdminAuthenticatedThemeRouteImport } from './routes/admin._authenticated.theme'
import { Route as AdminAuthenticatedSettingsRouteImport } from './routes/admin._authenticated.settings'
import { Route as AdminAuthenticatedSeoRouteImport } from './routes/admin._authenticated.seo'
import { Route as AdminAuthenticatedPwaRouteImport } from './routes/admin._authenticated.pwa'
import { Route as AdminAuthenticatedPostsRouteImport } from './routes/admin._authenticated.posts'
import { Route as AdminAuthenticatedPagesRouteImport } from './routes/admin._authenticated.pages'
import { Route as AdminAuthenticatedNotificationsRouteImport } from './routes/admin._authenticated.notifications'
import { Route as AdminAuthenticatedNewsletterRouteImport } from './routes/admin._authenticated.newsletter'
import { Route as AdminAuthenticatedMediaRouteImport } from './routes/admin._authenticated.media'
import { Route as AdminAuthenticatedMaintenanceRouteImport } from './routes/admin._authenticated.maintenance'
import { Route as AdminAuthenticatedIntegrationsRouteImport } from './routes/admin._authenticated.integrations'
import { Route as AdminAuthenticatedCookiesRouteImport } from './routes/admin._authenticated.cookies'
import { Route as AdminAuthenticatedCommentsRouteImport } from './routes/admin._authenticated.comments'
import { Route as AdminAuthenticatedCacheRouteImport } from './routes/admin._authenticated.cache'
import { Route as AdminAuthenticatedBackupRouteImport } from './routes/admin._authenticated.backup'
import { Route as AdminAuthenticatedAnalyticsRouteImport } from './routes/admin._authenticated.analytics'
import { Route as AdminAuthenticatedPostsNewRouteImport } from './routes/admin._authenticated.posts.new'
import { Route as AdminAuthenticatedPostsIdEditRouteImport } from './routes/admin._authenticated.posts.$id.edit'
import { Route as AdminAuthenticatedPagesIdEditRouteImport } from './routes/admin._authenticated.pages.$id.edit'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedUsersRoute = AdminAuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedToolsRoute = AdminAuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedThemeRoute = AdminAuthenticatedThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedSettingsRoute =
  AdminAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedSeoRoute = AdminAuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedPwaRoute = AdminAuthenticatedPwaRouteImport.update({
  id: '/pwa',
  path: '/pwa',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedPostsRoute = AdminAuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedPagesRoute = AdminAuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedNotificationsRoute =
  AdminAuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedNewsletterRoute =
  AdminAuthenticatedNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMediaRoute = AdminAuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedMaintenanceRoute =
  AdminAuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedIntegrationsRoute =
  AdminAuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCookiesRoute =
  AdminAuthenticatedCookiesRouteImport.update({
    id: '/cookies',
    path: '/cookies',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCommentsRoute =
  AdminAuthenticatedCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedCacheRoute = AdminAuthenticatedCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedBackupRoute =
  AdminAuthenticatedBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedAnalyticsRoute =
  AdminAuthenticatedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedPostsNewRoute =
  AdminAuthenticatedPostsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAuthenticatedPostsRoute,
  } as any)
const AdminAuthenticatedPostsIdEditRoute =
  AdminAuthenticatedPostsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminAuthenticatedPostsRoute,
  } as any)
const AdminAuthenticatedPagesIdEditRoute =
  AdminAuthenticatedPagesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminAuthenticatedPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/analytics': typeof AdminAuthenticatedAnalyticsRoute
  '/admin/backup': typeof AdminAuthenticatedBackupRoute
  '/admin/cache': typeof AdminAuthenticatedCacheRoute
  '/admin/comments': typeof AdminAuthenticatedCommentsRoute
  '/admin/cookies': typeof AdminAuthenticatedCookiesRoute
  '/admin/integrations': typeof AdminAuthenticatedIntegrationsRoute
  '/admin/maintenance': typeof AdminAuthenticatedMaintenanceRoute
  '/admin/media': typeof AdminAuthenticatedMediaRoute
  '/admin/newsletter': typeof AdminAuthenticatedNewsletterRoute
  '/admin/notifications': typeof AdminAuthenticatedNotificationsRoute
  '/admin/pages': typeof AdminAuthenticatedPagesRouteWithChildren
  '/admin/posts': typeof AdminAuthenticatedPostsRouteWithChildren
  '/admin/pwa': typeof AdminAuthenticatedPwaRoute
  '/admin/seo': typeof AdminAuthenticatedSeoRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/theme': typeof AdminAuthenticatedThemeRoute
  '/admin/tools': typeof AdminAuthenticatedToolsRoute
  '/admin/users': typeof AdminAuthenticatedUsersRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/posts/new': typeof AdminAuthenticatedPostsNewRoute
  '/admin/pages/$id/edit': typeof AdminAuthenticatedPagesIdEditRoute
  '/admin/posts/$id/edit': typeof AdminAuthenticatedPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/analytics': typeof AdminAuthenticatedAnalyticsRoute
  '/admin/backup': typeof AdminAuthenticatedBackupRoute
  '/admin/cache': typeof AdminAuthenticatedCacheRoute
  '/admin/comments': typeof AdminAuthenticatedCommentsRoute
  '/admin/cookies': typeof AdminAuthenticatedCookiesRoute
  '/admin/integrations': typeof AdminAuthenticatedIntegrationsRoute
  '/admin/maintenance': typeof AdminAuthenticatedMaintenanceRoute
  '/admin/media': typeof AdminAuthenticatedMediaRoute
  '/admin/newsletter': typeof AdminAuthenticatedNewsletterRoute
  '/admin/notifications': typeof AdminAuthenticatedNotificationsRoute
  '/admin/pages': typeof AdminAuthenticatedPagesRouteWithChildren
  '/admin/posts': typeof AdminAuthenticatedPostsRouteWithChildren
  '/admin/pwa': typeof AdminAuthenticatedPwaRoute
  '/admin/seo': typeof AdminAuthenticatedSeoRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/theme': typeof AdminAuthenticatedThemeRoute
  '/admin/tools': typeof AdminAuthenticatedToolsRoute
  '/admin/users': typeof AdminAuthenticatedUsersRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/posts/new': typeof AdminAuthenticatedPostsNewRoute
  '/admin/pages/$id/edit': typeof AdminAuthenticatedPagesIdEditRoute
  '/admin/posts/$id/edit': typeof AdminAuthenticatedPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/_authenticated/analytics': typeof AdminAuthenticatedAnalyticsRoute
  '/admin/_authenticated/backup': typeof AdminAuthenticatedBackupRoute
  '/admin/_authenticated/cache': typeof AdminAuthenticatedCacheRoute
  '/admin/_authenticated/comments': typeof AdminAuthenticatedCommentsRoute
  '/admin/_authenticated/cookies': typeof AdminAuthenticatedCookiesRoute
  '/admin/_authenticated/integrations': typeof AdminAuthenticatedIntegrationsRoute
  '/admin/_authenticated/maintenance': typeof AdminAuthenticatedMaintenanceRoute
  '/admin/_authenticated/media': typeof AdminAuthenticatedMediaRoute
  '/admin/_authenticated/newsletter': typeof AdminAuthenticatedNewsletterRoute
  '/admin/_authenticated/notifications': typeof AdminAuthenticatedNotificationsRoute
  '/admin/_authenticated/pages': typeof AdminAuthenticatedPagesRouteWithChildren
  '/admin/_authenticated/posts': typeof AdminAuthenticatedPostsRouteWithChildren
  '/admin/_authenticated/pwa': typeof AdminAuthenticatedPwaRoute
  '/admin/_authenticated/seo': typeof AdminAuthenticatedSeoRoute
  '/admin/_authenticated/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/_authenticated/theme': typeof AdminAuthenticatedThemeRoute
  '/admin/_authenticated/tools': typeof AdminAuthenticatedToolsRoute
  '/admin/_authenticated/users': typeof AdminAuthenticatedUsersRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/posts/new': typeof AdminAuthenticatedPostsNewRoute
  '/admin/_authenticated/pages/$id/edit': typeof AdminAuthenticatedPagesIdEditRoute
  '/admin/_authenticated/posts/$id/edit': typeof AdminAuthenticatedPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/admin'
    | '/admin/login'
    | '/blog/$slug'
    | '/tools/$slug'
    | '/blog/'
    | '/tools/'
    | '/admin/analytics'
    | '/admin/backup'
    | '/admin/cache'
    | '/admin/comments'
    | '/admin/cookies'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/pwa'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/tools'
    | '/admin/users'
    | '/admin/'
    | '/admin/posts/new'
    | '/admin/pages/$id/edit'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/admin/login'
    | '/blog/$slug'
    | '/tools/$slug'
    | '/blog'
    | '/tools'
    | '/admin/analytics'
    | '/admin/backup'
    | '/admin/cache'
    | '/admin/comments'
    | '/admin/cookies'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/pwa'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/tools'
    | '/admin/users'
    | '/admin'
    | '/admin/posts/new'
    | '/admin/pages/$id/edit'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/blog/$slug'
    | '/tools/$slug'
    | '/blog/'
    | '/tools/'
    | '/admin/_authenticated/analytics'
    | '/admin/_authenticated/backup'
    | '/admin/_authenticated/cache'
    | '/admin/_authenticated/comments'
    | '/admin/_authenticated/cookies'
    | '/admin/_authenticated/integrations'
    | '/admin/_authenticated/maintenance'
    | '/admin/_authenticated/media'
    | '/admin/_authenticated/newsletter'
    | '/admin/_authenticated/notifications'
    | '/admin/_authenticated/pages'
    | '/admin/_authenticated/posts'
    | '/admin/_authenticated/pwa'
    | '/admin/_authenticated/seo'
    | '/admin/_authenticated/settings'
    | '/admin/_authenticated/theme'
    | '/admin/_authenticated/tools'
    | '/admin/_authenticated/users'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/posts/new'
    | '/admin/_authenticated/pages/$id/edit'
    | '/admin/_authenticated/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/users': {
      id: '/admin/_authenticated/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthenticatedUsersRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/tools': {
      id: '/admin/_authenticated/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminAuthenticatedToolsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/theme': {
      id: '/admin/_authenticated/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminAuthenticatedThemeRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/settings': {
      id: '/admin/_authenticated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthenticatedSettingsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/seo': {
      id: '/admin/_authenticated/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminAuthenticatedSeoRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/pwa': {
      id: '/admin/_authenticated/pwa'
      path: '/pwa'
      fullPath: '/admin/pwa'
      preLoaderRoute: typeof AdminAuthenticatedPwaRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/posts': {
      id: '/admin/_authenticated/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminAuthenticatedPostsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/pages': {
      id: '/admin/_authenticated/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminAuthenticatedPagesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/notifications': {
      id: '/admin/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAuthenticatedNotificationsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/newsletter': {
      id: '/admin/_authenticated/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminAuthenticatedNewsletterRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/media': {
      id: '/admin/_authenticated/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAuthenticatedMediaRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/maintenance': {
      id: '/admin/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminAuthenticatedMaintenanceRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/integrations': {
      id: '/admin/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminAuthenticatedIntegrationsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/cookies': {
      id: '/admin/_authenticated/cookies'
      path: '/cookies'
      fullPath: '/admin/cookies'
      preLoaderRoute: typeof AdminAuthenticatedCookiesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/comments': {
      id: '/admin/_authenticated/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminAuthenticatedCommentsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/cache': {
      id: '/admin/_authenticated/cache'
      path: '/cache'
      fullPath: '/admin/cache'
      preLoaderRoute: typeof AdminAuthenticatedCacheRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/backup': {
      id: '/admin/_authenticated/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminAuthenticatedBackupRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/analytics': {
      id: '/admin/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthenticatedAnalyticsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/posts/new': {
      id: '/admin/_authenticated/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminAuthenticatedPostsNewRouteImport
      parentRoute: typeof AdminAuthenticatedPostsRoute
    }
    '/admin/_authenticated/posts/$id/edit': {
      id: '/admin/_authenticated/posts/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminAuthenticatedPostsIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedPostsRoute
    }
    '/admin/_authenticated/pages/$id/edit': {
      id: '/admin/_authenticated/pages/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pages/$id/edit'
      preLoaderRoute: typeof AdminAuthenticatedPagesIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedPagesRoute
    }
  }
}

interface AdminAuthenticatedPagesRouteChildren {
  AdminAuthenticatedPagesIdEditRoute: typeof AdminAuthenticatedPagesIdEditRoute
}

const AdminAuthenticatedPagesRouteChildren: AdminAuthenticatedPagesRouteChildren =
  {
    AdminAuthenticatedPagesIdEditRoute: AdminAuthenticatedPagesIdEditRoute,
  }

const AdminAuthenticatedPagesRouteWithChildren =
  AdminAuthenticatedPagesRoute._addFileChildren(
    AdminAuthenticatedPagesRouteChildren,
  )

interface AdminAuthenticatedPostsRouteChildren {
  AdminAuthenticatedPostsNewRoute: typeof AdminAuthenticatedPostsNewRoute
  AdminAuthenticatedPostsIdEditRoute: typeof AdminAuthenticatedPostsIdEditRoute
}

const AdminAuthenticatedPostsRouteChildren: AdminAuthenticatedPostsRouteChildren =
  {
    AdminAuthenticatedPostsNewRoute: AdminAuthenticatedPostsNewRoute,
    AdminAuthenticatedPostsIdEditRoute: AdminAuthenticatedPostsIdEditRoute,
  }

const AdminAuthenticatedPostsRouteWithChildren =
  AdminAuthenticatedPostsRoute._addFileChildren(
    AdminAuthenticatedPostsRouteChildren,
  )

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedAnalyticsRoute: typeof AdminAuthenticatedAnalyticsRoute
  AdminAuthenticatedBackupRoute: typeof AdminAuthenticatedBackupRoute
  AdminAuthenticatedCacheRoute: typeof AdminAuthenticatedCacheRoute
  AdminAuthenticatedCommentsRoute: typeof AdminAuthenticatedCommentsRoute
  AdminAuthenticatedCookiesRoute: typeof AdminAuthenticatedCookiesRoute
  AdminAuthenticatedIntegrationsRoute: typeof AdminAuthenticatedIntegrationsRoute
  AdminAuthenticatedMaintenanceRoute: typeof AdminAuthenticatedMaintenanceRoute
  AdminAuthenticatedMediaRoute: typeof AdminAuthenticatedMediaRoute
  AdminAuthenticatedNewsletterRoute: typeof AdminAuthenticatedNewsletterRoute
  AdminAuthenticatedNotificationsRoute: typeof AdminAuthenticatedNotificationsRoute
  AdminAuthenticatedPagesRoute: typeof AdminAuthenticatedPagesRouteWithChildren
  AdminAuthenticatedPostsRoute: typeof AdminAuthenticatedPostsRouteWithChildren
  AdminAuthenticatedPwaRoute: typeof AdminAuthenticatedPwaRoute
  AdminAuthenticatedSeoRoute: typeof AdminAuthenticatedSeoRoute
  AdminAuthenticatedSettingsRoute: typeof AdminAuthenticatedSettingsRoute
  AdminAuthenticatedThemeRoute: typeof AdminAuthenticatedThemeRoute
  AdminAuthenticatedToolsRoute: typeof AdminAuthenticatedToolsRoute
  AdminAuthenticatedUsersRoute: typeof AdminAuthenticatedUsersRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedAnalyticsRoute: AdminAuthenticatedAnalyticsRoute,
  AdminAuthenticatedBackupRoute: AdminAuthenticatedBackupRoute,
  AdminAuthenticatedCacheRoute: AdminAuthenticatedCacheRoute,
  AdminAuthenticatedCommentsRoute: AdminAuthenticatedCommentsRoute,
  AdminAuthenticatedCookiesRoute: AdminAuthenticatedCookiesRoute,
  AdminAuthenticatedIntegrationsRoute: AdminAuthenticatedIntegrationsRoute,
  AdminAuthenticatedMaintenanceRoute: AdminAuthenticatedMaintenanceRoute,
  AdminAuthenticatedMediaRoute: AdminAuthenticatedMediaRoute,
  AdminAuthenticatedNewsletterRoute: AdminAuthenticatedNewsletterRoute,
  AdminAuthenticatedNotificationsRoute: AdminAuthenticatedNotificationsRoute,
  AdminAuthenticatedPagesRoute: AdminAuthenticatedPagesRouteWithChildren,
  AdminAuthenticatedPostsRoute: AdminAuthenticatedPostsRouteWithChildren,
  AdminAuthenticatedPwaRoute: AdminAuthenticatedPwaRoute,
  AdminAuthenticatedSeoRoute: AdminAuthenticatedSeoRoute,
  AdminAuthenticatedSettingsRoute: AdminAuthenticatedSettingsRoute,
  AdminAuthenticatedThemeRoute: AdminAuthenticatedThemeRoute,
  AdminAuthenticatedToolsRoute: AdminAuthenticatedToolsRoute,
  AdminAuthenticatedUsersRoute: AdminAuthenticatedUsersRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
